JavaScript: true
Ruby: false
Python: false
PHP: false

engines:
  eslint:
    enabled: true

ratings:
   paths:
   - "**.js"

exclude_paths:
- src/**/*.spec.js
- docs/**/*
- documentation/**/*
- dist/**/*
- e2e/**/*
- karma.conf.js