version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
            FIREFOX_BIN: "/usr/bin/firefox"
    working_directory: ~/gluebert
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8.4-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
            FIREFOX_BIN: "/usr/bin/firefox"
    working_directory: ~/gluebert
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: npm install codeclimate-test-reporter
      - run:
          name: code-coverage
          command: './node_modules/.bin/codeclimate-test-reporter < ./coverage/phantomjs/lcov.info'
      - run: yarn test
      - run: npm install codeclimate-test-reporter
  saucelabs:
    docker:
      - image: circleci/node:8.4-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
            FIREFOX_BIN: "/usr/bin/firefox"
    working_directory: ~/gluebert
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:e2e:saucelabs
  documentation_build:
    docker:
      - image: circleci/node:8.4-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
            FIREFOX_BIN: "/usr/bin/firefox"
    working_directory: ~/gluebert
    steps:
      - checkout
      - run: cd ./documentation/themes/gluebert && npm install
      - run: cd ./documentation/themes/gluebert && npm run build
  documentation_deploy:
    docker:
      - image: felicianotech/docker-hugo:0.26
    working_directory: ~/gluebert
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/gluebert/documentation/
      - run: ws s3 sync ~/gluebert/documentation/public s3://gluebert.com --delete
workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - saucelabs:
          filters:
            branches:
              only:
                - master
      - documentation_build
      - documentation_deploy:
         requires:
           - documentation_build